spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-17farm.cgzeg2t2eys7.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId:
            clientSecret:
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/kakao # "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: jihoon-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            trace
jwt:
  secret-key:
server:
  servlet:
    encoding:
      force-response: true
