spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/17farm?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            trace
cloud:
  aws:
    credentials:
      access-key: AKIA4JNU3KAC276RKFPR
      secret-key: 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
    s3:
      bucket: jihoon-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false