server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
cloud:
  aws:
    credentials:
      access-key: ${ AWS_ACCESS_KEY }
      secret-key: ${ AWS_SECRET_ACCESS_KEY }
    s3:
      bucket: jihoon-bucket
      dir:
    region:
      static: ap-northeast-2
    stack:
      auto:false