spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/17farm?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            adminKey:
            clientId:
            clientSecret:
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/kakao # "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            trace
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: jihoon-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  secret-key:
server:
  servlet:
    encoding:
      force-response: true
mail:
  smtp:
    auth: true
    host: smtp.gmail.com
    port: 465
    starttls:
      enable: true
      required: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
AdminMail:
  id:
  password: